[package]
name = "http2sql"
version = "0.1.0"
edition = "2021"

[dependencies]
# Web framework
actix-web = "4"

# Database
sqlx = { version = "0.7", features = ["runtime-tokio", "mysql", "chrono", "macros", "json"] }

# Async runtime
tokio = { version = "1", features = ["full"] }

# Utilities
chrono = { version = "0.4", features = ["serde"] }
dotenv = "0.15"
num_cpus = "1"

# Serialization
serde = { version = "1", features = ["derive"] }
serde_json = "1"

# Logging
log = "0.4"
env_logger = "0.10"