[package]
name = "http2sql"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
serde = { version = "1", features = ["derive"] }
sqlx = { version = "0", features = ["runtime-tokio-rustls", "mysql", "chrono"] }
dotenv = "0"
chrono = { version = "0", features = ["serde"] }
num_cpus = "1"