[package]
name = "http2sql"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
chrono = { version = "0", features = ["serde"] }
dotenv = "0"
num_cpus = "1"
serde = { version = "1", features = ["derive"] }
sqlx = { version = "0", features = ["runtime-tokio", "mysql", "chrono", "macros"] }
tokio = { version = "1", features = ["full"] }