services:
  http2sql:
    build:
      context: .
      dockerfile: dockerfile
    image: ghcr.io/excoffierleonard/http2sql
    container_name: http2sql-app
    restart: unless-stopped
    depends_on:
      - db
    environment:
      HTTP2SQL_DATABASE_URL: ${HTTP2SQL_DATABASE_URL:-mysql://http2sql:http2sql@db:3306/http2sql}
    ports:
      - "8080:8080"
    networks:
      - http2sql
    
  # Here MariaDB is used as an example of a database service for devlopment purposes, in production you may use an external database service and delete this section.
  db:
    image: mariadb
    container_name: http2sql-db
    restart: unless-stopped
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
      MARIADB_DATABASE: ${HTTP2SQL_DB_NAME:-http2sql}
      MARIADB_USER: ${HTTP2SQL_DB_USER:-http2sql}
      MARIADB_PASSWORD: ${HTTP2SQL_DB_PASSWORD:-http2sql}
    ports:
      - "${HTTP2SQL_DB_PORT:-3306}:3306"
    volumes:
      - http2sql-db:/var/lib/mysql
    networks:
      - http2sql
    
volumes:
  http2sql-db:
    name: http2sql-db

networks:
  http2sql:
    name: http2sql